### ISSUE TITLE
Code Generation does not work in VS 2015

### ISSUE THREAD

**Issue by MNJason** [bbsimonbb/query-first#2]
Steps:
1) Using QueryFirst template file 
2) Connecting to SQL database
3) Write Query
4) Save query.sql file 

At step 4, the QueryFirst output window shows the following error:

Object reference not set to an instance of an object.
   at QueryFirst.CodeGenerationContext.get_DesignTimeConnectionString() in C:\dev\QueryFirst\query-first\QueryFirst\CodeGenerationContext.cs:line 113
   at QueryFirst.Conductor.Process() in C:\dev\QueryFirst\query-first\QueryFirst\Conductor.cs:line 49

**Comment by bbsimonbb** [comment]
Ok that's a simple one. You need a connection string named
QfDefaultConnection in your app or web.config. I need to do a nicer error
sometime. You will also need to create a class QfRuntimeConnection, with a
static method GetConnectionString().

Good luck.

2016-08-04 20:06 GMT+02:00 MNJ <notifications@github.com>:

**Comment by MNJason** [comment]
Thanks, that solves it.  Also, I could not find this documented (example form) anywhere except the comments area of codeproject -- YouTube video does not show this.

**Comment by bbsimonbb** [comment]
I've just put in the readme on github. It's at the end of the blurb on the
MS gallery page, but you're right, it needs better treatment.

Happy coding. I'd be pleased to hear your reactions.

Simon

2016-08-04 23:09 GMT+02:00 MNJ <notifications@github.com>:
