### ISSUE TITLE
New project console: unable to resolve ueryFirst.IProvider at TinyIOC

### ISSUE THREAD

**Issue by figueiredorj** [bbsimonbb/query-first#26]
On a fresh project console when running "save" i got followig exception on queryfirst:
`Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Unable to resolve type: QueryFirst.IProvider   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 3773
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1854
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType](String name) in C:\mydev\QueryFirstV\QueryFirst\TinyIoC.cs:line 1975
   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255`

Somthing not right.. currently no dependency on tinyioc as it is a fresh project...

**Comment by figueiredorj** [comment]
Able to solve it.. related to misplaced fle of QfRuntimeConnection
