### ISSUE TITLE
Cannot use temp table in query?

### ISSUE THREAD

**Issue by efurban** [bbsimonbb/query-first#66]
Hi, 

It seems that I couldn't use any temp table in the query. For example: I have two temp tables in the stored proc that I call from the FirstQuery SQL file, however it gives me error when building.  Is this a limitation or perhaps I am not doing it correctly?  

**Query**
`/* .sql query managed by QueryFirst add-in */
-- designTime - put parameter declarations and design time initialization here
declare @workdate date = getdate() 
set @workdate = getdate()
-- endDesignTime
EXEC dbo.pr_get_repo_margin_summary @workdate
`
**Error**
`Invalid object name '#bod'.
-----------------------------------------------------------
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
`

**Comment by AdrianBathurst** [comment]
Indeed it seems temp tables aren't supported. I guess the limitation is because QF interrogates the db for table schema structure. Obviously the temp table schema doesn't exist in the db, so it can't build the structure.

**Comment by efurban** [comment]
I wish there is a way to manually instruct QF the schema structure.

**Comment by bbsimonbb** [comment]
Hi there, sorry to leave you hanging. Yep this is a limitation. When we set the schema-discovery flag, SQL Server won't execute statements with temp tables, I imagine because they have side effects. My idea for how to deal with this was to run it in a transaction then rollback. EF will discover the return schema of these statements, so it should be doable. Any suggestions?

**Comment by AdrianBathurst** [comment]
👍 Would be nice if it could be done. No suggestions at the mo I'm afraid.

It is bizarre that it will let you use schema-discovery for an arbitrary statement like `select 1 A, 2 B union all select 3, 4;` but not for a temp table.

**Comment by AdrianBathurst** [comment]
Table Variables are supported, you could use that instead.

**Comment by efurban** [comment]
> Hi there, sorry to leave you hanging. Yep this is a limitation. When we set the schema-discovery flag, SQL Server won't execute statements with temp tables, I imagine because they have side effects. My idea for how to deal with this was to run it in a transaction then rollback. EF will discover the return schema of these statements, so it should be doable. Any suggestions?

I think that's a great idea!  Hope to see this implemented in the near future as now I have to use two different frameworks. 
Again, really love QF !
